// Copyright (c) 2024 Soft Biophysics Group LPTMS
// Part of frusa_mc, released under BSD 3-Clause License.

#ifndef FCC_GEOMETRY_HEADER_H
#define FCC_GEOMETRY_HEADER_H

#include "vector_utils.h"
#include <iostream>
#include <map>

using BondIndexMap = std::map<std::array<int,3> , unsigned int>;
namespace geometry_space {
  namespace fcc_space {

    struct bond_structure {
      // Generated by: ../../python/scripts/generate_fcc_permutations.py
      static inline const vec2i bond_permutation = {
          {0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11,
           12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},  // E
          {2,  9,  4, 10, 0,  19, 16, 1,  23, 7, 21, 6,
           18, 17, 8, 13, 11, 15, 20, 22, 12, 3, 5,  14},    // C3(X+Z)-
          {4,  7,  0,  21, 2, 22, 11, 9, 14, 1,  3,  16,
           20, 15, 23, 17, 6, 13, 12, 5, 18, 10, 19, 8},     // C3(X+Z)-^2
          {6,  5,  20, 1,  23, 3, 8, 10, 0,  15, 17, 2,
           14, 21, 16, 22, 12, 7, 4, 13, 11, 19, 9,  18},    // C3(-X-Z)
          {8,  3,  11, 5, 18, 1,  0,  17, 6, 22, 7,  20,
           16, 19, 12, 9, 14, 10, 23, 21, 2, 13, 15, 4},     // C3(-X-Z)^2
          {10, 23, 19, 6,  9,  20, 15, 2,  5,  16, 12, 1,
           22, 11, 7,  18, 21, 8,  3,  14, 17, 4,  0,  13},  // C4Z-
          {12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
           0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11},  // C2Z
          {14, 21, 16, 22, 12, 7, 4, 13, 11, 19, 9,  18,
           6,  5,  20, 1,  23, 3, 8, 10, 0,  15, 17, 2},     // C2Z * C3(X+Z)-
          {16, 19, 12, 9, 14, 10, 23, 21, 2, 13, 15, 4,
           8,  3,  11, 5, 18, 1,  0,  17, 6, 22, 7,  20},    // C2Z * C3(X+Z)-^2
          {18, 17, 8, 13, 11, 15, 20, 22, 12, 3, 5,  14,
           2,  9,  4, 10, 0,  19, 16, 1,  23, 7, 21, 6},     // C2Z * C3(-X-Z)
          {20, 15, 23, 17, 6, 13, 12, 5, 18, 10, 19, 8,
           4,  7,  0,  21, 2, 22, 11, 9, 14, 1,  3,  16},    // C2Z * C3(-X-Z)^2
          {22, 11, 7,  18, 21, 8,  3,  14, 17, 4,  0,  13,
           10, 23, 19, 6,  9,  20, 15, 2,  5,  16, 12, 1},   // C2Z * C4Z-
      };  // bond_permutation

      static inline const vec2i bond_array {
        {  1,  0,  0 },
        {  0,  1,  0 },
        {  0,  0,  1 },
        {  1,  0, -1 },
        {  1, -1,  0 },
        {  0,  1, -1 },
        { -1,  0,  0 },
        {  0, -1,  0 },
        {  0,  0, -1 },
        { -1,  0,  1 },
        { -1,  1,  0 },
        {  0, -1,  1 },
      }; // bond_array

      static inline const BondIndexMap bond_index {
        { {  1,  0,  0 }, 0 },
        { {  0,  1,  0 }, 1 },
        { {  0,  0,  1 }, 2 },
        { {  1,  0, -1 }, 3 },
        { {  1, -1,  0 }, 4 },
        { {  0,  1, -1 }, 5 },
        { { -1,  0,  0 }, 6 },
        { {  0, -1,  0 }, 7 },
        { {  0,  0, -1 }, 8 },
        { { -1,  0,  1 }, 9 },
        { { -1,  1,  0 }, 10 },
        { {  0, -1,  1 }, 11 }
      }; // bond_index

      static inline const vec1i opposite_bonds {
          6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5};
    }; // bond_structure
static constexpr int n_neighbours {12};
static constexpr int n_orientations {24};
  } // fcc_space
} // geometry_space

#endif // FCC_GEOMETRY_HEADER_H
